name: 'Label Actions'

on:
  issues:
    types: [labeled]
  discussion:
    types: [labeled]
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  issues: write
  discussions: write
  pull-requests: write

jobs:
  reaction:
    runs-on: hla1-talos
    steps:
      - uses: dessant/label-actions@102faf474a544be75fbaf4df54e73d3c515a0e65 # v4.0.1
        with:
          github-token: ${{ github.token }}
